import { Column, Entity, Index } from 'typeorm';
import { AppBaseEntity } from '../../../shared/database/base.entity';

export type FileScope =
  | 'attachment' // attached to an AI prompt, chat message, or coworker run
  | 'document' // a document generated by the AI (docx/xlsx/pdf/etc.)
  | 'system_asset' // source/asset of a generated running system
  | 'avatar'
  | 'other';

@Entity({ name: 'files' })
@Index(['organizationId', 'scope'])
export class FileEntity extends AppBaseEntity {
  @Column({ name: 'organization_id', type: 'uuid' })
  organizationId!: string;

  @Column({ name: 'workspace_id', type: 'uuid', nullable: true })
  workspaceId!: string | null;

  @Column({ name: 'system_id', type: 'uuid', nullable: true })
  systemId!: string | null;

  @Column({ type: 'varchar', length: 40, default: 'attachment' })
  scope!: FileScope;

  @Column({ type: 'varchar', length: 512 })
  filename!: string;

  @Column({ name: 'mime_type', type: 'varchar', length: 180 })
  mimeType!: string;

  @Column({ type: 'bigint' })
  size!: string; // stored as bigint, exposed as string

  @Column({ name: 'storage_path', type: 'varchar', length: 1024 })
  storagePath!: string;

  /** Sha-256 hex digest for dedup / integrity. */
  @Column({ type: 'varchar', length: 128, nullable: true })
  checksum!: string | null;

  /** Optional linkage to an AI change request, coworker run, message, etc. */
  @Column({ name: 'owner_kind', type: 'varchar', length: 60, nullable: true })
  ownerKind!: string | null;

  @Column({ name: 'owner_id', type: 'uuid', nullable: true })
  ownerId!: string | null;

  @Column({ type: 'jsonb', nullable: true })
  metadata!: Record<string, unknown> | null;

  @Column({ name: 'uploaded_by_user_id', type: 'uuid', nullable: true })
  uploadedByUserId!: string | null;

  @Column({ type: 'varchar', length: 30, default: 'active' })
  status!: string;
}
