import type { PlanEntity } from './entities/plan.entity';

type PlanSeed = Omit<
  PlanEntity,
  | 'id'
  | 'createdAt'
  | 'updatedAt'
  | 'deletedAt'
  | 'stripeMonthlyPriceId'
  | 'stripeYearlyPriceId'
> & {
  stripeMonthlyPriceId?: null;
  stripeYearlyPriceId?: null;
};

export const SEED_PLANS: PlanSeed[] = [
  {
    tier: 'free',
    name: 'Free',
    tagline: 'Try Stack62 with one of each AI feature on us.',
    monthlyPriceCents: 0,
    yearlyPriceCents: 0,
    currency: 'USD',
    perSeat: false,
    maxMembers: 1,
    monthlyAiRequests: 1, // 1 AI request total during the trial
    maxActiveSystems: 1,
    storageGb: 1,
    maxWorkflows: 1,
    auditRetentionDays: 7,
    allowPremiumIntegrations: false,
    allowSso: false,
    supportLevel: 'community',
    isPublished: true,
    sortOrder: 10,
    features: [
      '1 AI plan generation (lifetime)',
      '1 generated document (lifetime)',
      '1 deployed system',
      '1 GB storage',
      'Community support',
    ],
    stripeMonthlyPriceId: null,
    stripeYearlyPriceId: null,
  },
  {
    tier: 'starter',
    name: 'Starter',
    tagline: 'For small teams just getting started with Stack62.',
    monthlyPriceCents: 1900,
    yearlyPriceCents: 19000,
    currency: 'USD',
    perSeat: true,
    maxMembers: 5,
    monthlyAiRequests: 1000,
    maxActiveSystems: 3,
    storageGb: 10,
    maxWorkflows: 5,
    auditRetentionDays: 30,
    allowPremiumIntegrations: false,
    allowSso: false,
    supportLevel: 'email',
    isPublished: true,
    sortOrder: 20,
    features: [
      'Up to 5 members',
      '1,000 AI requests / month',
      '3 active systems',
      '10 GB storage',
      'Core integrations (Gmail, WhatsApp, Slack)',
      '30-day audit log retention',
      'Email support',
    ],
    stripeMonthlyPriceId: null,
    stripeYearlyPriceId: null,
  },
  {
    tier: 'pro',
    name: 'Pro',
    tagline: 'For growing teams shipping serious operational software.',
    monthlyPriceCents: 4900,
    yearlyPriceCents: 49000,
    currency: 'USD',
    perSeat: true,
    maxMembers: 20,
    monthlyAiRequests: 10_000,
    maxActiveSystems: -1,
    storageGb: 100,
    maxWorkflows: -1,
    auditRetentionDays: 90,
    allowPremiumIntegrations: true,
    allowSso: false,
    supportLevel: 'priority',
    isPublished: true,
    sortOrder: 30,
    features: [
      'Up to 20 members',
      '10,000 AI requests / month',
      'Unlimited active systems',
      '100 GB storage',
      'All integrations (incl. QuickBooks, Stripe, Salesforce)',
      'Unlimited workflows',
      '90-day audit log retention',
      'Priority email + chat support',
    ],
    stripeMonthlyPriceId: null,
    stripeYearlyPriceId: null,
  },
  {
    tier: 'business',
    name: 'Business',
    tagline:
      'For organizations with serious data, compliance, and team-size needs.',
    monthlyPriceCents: 9900,
    yearlyPriceCents: 99000,
    currency: 'USD',
    perSeat: true,
    maxMembers: 100,
    monthlyAiRequests: 50_000,
    maxActiveSystems: -1,
    storageGb: 500,
    maxWorkflows: -1,
    auditRetentionDays: 365,
    allowPremiumIntegrations: true,
    allowSso: false,
    supportLevel: 'csm',
    isPublished: true,
    sortOrder: 40,
    features: [
      'Up to 100 members',
      '50,000 AI requests / month',
      '500 GB storage',
      'Everything in Pro',
      'Custom integrations',
      '1-year audit log retention',
      'Dedicated CSM',
    ],
    stripeMonthlyPriceId: null,
    stripeYearlyPriceId: null,
  },
  {
    tier: 'enterprise',
    name: 'Enterprise',
    tagline:
      "Designed for organizations that need SSO, custom deployment, and 24/7 support.",
    monthlyPriceCents: 0, // contact sales
    yearlyPriceCents: 0,
    currency: 'USD',
    perSeat: true,
    maxMembers: -1,
    monthlyAiRequests: -1,
    maxActiveSystems: -1,
    storageGb: 5000,
    maxWorkflows: -1,
    auditRetentionDays: 36500,
    allowPremiumIntegrations: true,
    allowSso: true,
    supportLevel: 'enterprise',
    isPublished: true,
    sortOrder: 50,
    features: [
      'Unlimited members',
      'Unlimited AI requests',
      'Unlimited storage (custom)',
      'SSO / SAML',
      'Dedicated infrastructure (optional)',
      '24/7 support with SLA',
      'Custom contracts and DPA',
    ],
    stripeMonthlyPriceId: null,
    stripeYearlyPriceId: null,
  },
];
